# AUTOGENERATED FILE - DO NOT EDIT
# This file uses {{ .Style }} format.
{{- if eq .Style "wgquick"}}
# See https://man7.org/linux/man-pages/man8/wg-quick.8.html#CONFIGURATION
{{- end}}
# Lines starting with the -WGP- tag are used by
# the WireGuard Portal configuration parser.

# -WGP- WIREGUARD PORTAL CONFIGURATION FILE
# -WGP- version {{ .Portal.Version }}

[Interface]
# -WGP- Peer: {{.Peer.Identifier}}
# -WGP- Created: {{.Peer.CreatedAt}}
# -WGP- Updated: {{.Peer.UpdatedAt}}
# -WGP- Display name: {{ .Peer.DisplayName }}
# -WGP- PublicKey: {{ .Peer.Interface.KeyPair.PublicKey }}
{{- if eq .Peer.Interface.Type "server"}}
# -WGP- Peer type: server
{{else}}
# -WGP- Peer type: client
{{- end}}

# Core settings
PrivateKey = {{ .Peer.Interface.KeyPair.PrivateKey }}
{{- if eq .Style "wgquick"}}
Address = {{ CidrsToString .Peer.Interface.Addresses }}
{{- end}}

# Misc. settings (optional)
{{- if or (eq .Style "wgquick") (eq .Style "amneziawg")}}
{{- if .Peer.Interface.DnsStr.GetValue}}
DNS = {{ .Peer.Interface.DnsStr.GetValue }} {{- if .Peer.Interface.DnsSearchStr.GetValue}}, {{ .Peer.Interface.DnsSearchStr.GetValue }} {{- end}}
{{- end}}
{{- if ne .Peer.Interface.Mtu.GetValue 0}}
MTU = {{ .Peer.Interface.Mtu.GetValue }}
{{- end}}
{{- if ne .Peer.Interface.RoutingTable.GetValue ""}}
Table = {{ .Peer.Interface.RoutingTable.GetValue }}
{{- end}}
{{- end}}
{{- if ne .Peer.Interface.FirewallMark.GetValue 0}}
FwMark = {{ .Peer.Interface.FirewallMark.GetValue }}
{{- end}}

{{- if and (eq .Style "amneziawg") .AmneziaExtras }}

# AmneziaWG V2 obfuscation parameters — must match the server-side values.
# See https://github.com/amnezia-vpn/amneziawg-go for protocol details.
{{- with .AmneziaExtras }}
{{- if ne .Jc 0}}
Jc = {{ .Jc }}
{{- end}}
{{- if ne .Jmin 0}}
Jmin = {{ .Jmin }}
{{- end}}
{{- if ne .Jmax 0}}
Jmax = {{ .Jmax }}
{{- end}}
{{- if ne .S1 0}}
S1 = {{ .S1 }}
{{- end}}
{{- if ne .S2 0}}
S2 = {{ .S2 }}
{{- end}}
{{- if ne .S3 0}}
S3 = {{ .S3 }}
{{- end}}
{{- if ne .S4 0}}
S4 = {{ .S4 }}
{{- end}}
{{- if ne .H1 0}}
H1 = {{ .H1 }}
{{- end}}
{{- if ne .H2 0}}
H2 = {{ .H2 }}
{{- end}}
{{- if ne .H3 0}}
H3 = {{ .H3 }}
{{- end}}
{{- if ne .H4 0}}
H4 = {{ .H4 }}
{{- end}}
{{- if ne .I1 ""}}
I1 = {{ .I1 }}
{{- end}}
{{- if ne .I2 ""}}
I2 = {{ .I2 }}
{{- end}}
{{- if ne .I3 ""}}
I3 = {{ .I3 }}
{{- end}}
{{- if ne .I4 ""}}
I4 = {{ .I4 }}
{{- end}}
{{- if ne .I5 ""}}
I5 = {{ .I5 }}
{{- end}}
{{- end}}
{{- end}}

{{- if eq .Style "wgquick"}}
# Interface hooks (optional)
{{- if .Peer.Interface.PreUp.GetValue}}
PreUp = {{ .Peer.Interface.PreUp.GetValue }}
{{- end}}
{{- if .Peer.Interface.PostUp.GetValue}}
PostUp = {{ .Peer.Interface.PostUp.GetValue }}
{{- end}}
{{- if .Peer.Interface.PreDown.GetValue}}
PreDown = {{ .Peer.Interface.PreDown.GetValue }}
{{- end}}
{{- if .Peer.Interface.PostDown.GetValue}}
PostDown = {{ .Peer.Interface.PostDown.GetValue }}
{{- end}}
{{- end}}

[Peer]
PublicKey = {{ .Peer.EndpointPublicKey.GetValue }}
Endpoint = {{ .Peer.Endpoint.GetValue }}
{{- if .Peer.AllowedIPsStr.GetValue}}
AllowedIPs = {{ .Peer.AllowedIPsStr.GetValue }}
{{- end}}
{{- if .Peer.PresharedKey}}
PresharedKey = {{ .Peer.PresharedKey }}
{{- end}}
{{- if and (ne .Peer.PersistentKeepalive.GetValue 0) (eq .Peer.Interface.Type "client")}}
PersistentKeepalive = {{ .Peer.PersistentKeepalive.GetValue }}
{{- end}}
